-- Active: 1748246424675@@localhost@3306@linktree
CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    profile_picture VARCHAR(255)
) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS link (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    label VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    user_id INT NOT NULL
) ENGINE = INNODB;
ALTER TABLE link
ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id);